import { Inter } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import Navbar from "./(components)/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <title>FirstNextApp</title>
    </head>
      <body className={inter.className}>
        <Navbar/>
        {children}
          <h2 className="bg-slate-700 text-3xl bottom-0 p-10 text-center font-extrabold ">Footer</h2>
        </body>
    </html>
  );
}
